### ISSUE TITLE
Two languages being returned when using "localeOverride"

### ISSUE THREAD

**Issue by mihai-honceriu** [phrase/ios-sdk#42] opened 2022-05-04 08:57 UTC
Short summary of our setup: 

- We want to have an in-app language picker
- We are using R.swift for strong typed resources

To reproduce the issue, I have to:
1) Set language in iOS Settings -> Our app to anything other than "English"
2) Set in-app language (localeOverride) to "en"
Result is: most of the strings are in english, but some of them will use the language in iOS Settings instead of the localeOverride.

I am properly settings the localeOverride and updating the translations using `updateTranslations` and then reloading the UI, but i cannot get it to work.

A suggestion i got from Phrase support was to use 
`NSLocalizedString("", comment: "")` instead of 
`NSLocalizedString("", bundle: hostingBundle, comment: "")` 

but unfortunately this would not be a solution for us as we cannot and would not like to change the Rswift code. 

Even so, I did a test using a breakpoint and using the method without the bundle would still return the translation in the wrong language, so i believe it would actually not solve the issue? I attached a screenshot.

![Screenshot 2022-04-28 at 16 33 47](https://user-images.githubusercontent.com/73482646/166650881-c016c512-39e2-4080-9bed-298bb5f33c7c.png)

We really want to release our in-app language picker to synchronize the language with the other platforms and our backend, but this issue is really blocking us! We have been on with support for like a month now with no solution. Please let me know if this is a known issue or if you need more details.

**Comment by theSoenke** [comment] 2022-05-05 06:47
Hi @mihai-honceriu, you are already using version 4.0.1 correct? @winkelsdorf Could you maybe take a look at what might be the cause for the reported issue here?

**Comment by winkelsdorf** [comment] 2022-05-05 08:01
Hi @mihai-honceriu. Thank you for your valuable feedback regarding using R.Swift together with the Phrase SDK. 

As @theSoenke said, could you please confirm the version of the Phrase SDK you are using? Best together with your R.Swift Version, the Xcode Version (which gives us a hint about the used Swift Version) and the minimum supported target iOS Version?

I think we need to separate this into two parts. 

1) First we have R.Swift with **multiple bundles** from what I see. Multiple bundles is something we currently don't support (see https://github.com/phrase/ios-sdk/issues/25 for a similar request). 

This is due to the fact that our SDK cannot swizzle different bundles safely without knowledge about them and their implementation. Even without swizzling using `Phrase.shared.localizedString(:)` to translate, it would need a major logic change in the SDK _and_ the OTA to support different bundles (beside other issues, translations would get merged for different bundles).

2) R.Swift uses `NSLocalizedString()` which is only supported for the main bundle from our SDK. I think this interferes here. From what I read a known issue, but there may be workaround. See https://github.com/mac-cain13/R.swift/issues/466, https://github.com/mac-cain13/R.swift/issues/219 and especially the merged PR https://github.com/mac-cain13/R.swift/pull/553.

That said, I think we should investigate your issue and try to find a working solution? @theSoenke

**Comment by mihai-honceriu** [comment] 2022-05-05 08:49
Hey and thank you for the swift answer!

I am using: Phrase: 4.0.1-rc.1, Rswift: 6.1.0, Xcode: 13.3, Swift 5, Min iOS 13

From what I understand from https://github.com/mac-cain13/R.swift/pull/553 , using the `preferredLanguages` of R.swift would actually bring us to the issue number 1. Depending on the `preferredLanguage` passed to R, it will use a bundle other than the main bundle. I have tried using the preferredLanguage of R.swift and the OTA would simply not work, the app would use only the local `strings` files. 

When not passing a preferredLanguage, R.swift uses the `hostingBundle` (as you can see in the generated code above). I made a new screenshot printing the hostingBundle which I believe is always the main bundle:

`fileprivate static let hostingBundle = Bundle(for: R.Class.self)`

<img width="777" alt="Screenshot 2022-05-05 at 11 13 35" src="https://user-images.githubusercontent.com/73482646/166885419-447f7c5a-8135-4a72-93b4-05f8f9a5ad6d.png">

Initially I believed it was working. I had my iOS set to "English" so the app was also automatically set to "English". This way, changing the language using Phrase's `localeOverride` worked without problems: it would fully use whatever language i select in-app after doing a Phrase `updateTranslations` and reloading the UI.

What might be interesting to notice is that issues appear **only** when I select:
- iOS Setting -> My app -> language **other** than "English"
- in-app (localeOverride) -> language "English"

e.g: 
iOS Settings: German, localeOverride: English. Result: Some translations are in german
iOS Settings: French, localeOverride: English. Result: Some translations are in french (always the same strings as above, so somehow it's not random strings, always the same ones)
iOS Settings: Italy, localeOverride: English: Result: Some translations are in italy (same as above) 
etc. 

but for
iOS Settings: English, `localeOverride`: Any language : All strings in "Any language"
iOS Settings: Any language, `localeOverride`: Any language other than English : All strings in `localeOverride` language

**Comment by theSoenke** [comment] 2022-05-06 13:19
Thanks @winkelsdorf. I would say we should then investigate how we could handle this. Would be great if you could look into this

**Comment by mihai-honceriu** [comment] 2022-05-17 14:05
Hello, is there any update on this issue? We are still not being able to deliver our in-app language change and cross-platform language sync because of it.

**Comment by winkelsdorf** [comment] 2022-06-11 08:53
I tried your failing setup, e.g. iOS Settings: German, localeOverride: English. All of the delivered keys were correctly translated using R.swift to my set `localeOverride`.

See this example:

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1413291/173180880-1f354ac6-d450-4dda-91c7-087dc64ed1a2.png">

As a general setup suggestion can you please check that your App supports the needed languages from the iOS side?
Like this under Localizations:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1413291/173180952-cb4702b1-3e44-4aec-8a39-a4b9555b39be.png">

From what I can tell now, after evaluating usage with R.swift, I think it's a problem with the OTA setup, not the iOS SDK. I am very curious what your manual check of the downloaded files will return.

**Comment by mihai-honceriu** [comment] 2022-07-05 12:13
I'm sorry i closed the issue as completed by mistake. Could anyone re-open it? Sorry for that 😄 

@winkelsdorf @theSoenke

**Comment by winkelsdorf** [comment] 2022-07-05 12:15
@mihai-honceriu sure, no problem, reopened! Thank you very much for your detailed answer, I'll have a deeper look into that later too.

**Comment by winkelsdorf** [comment] 2023-01-15 22:41
@mihai-honceriu I was unable to find anything related to those issues, not even able to replicate it. Were you able to find the issue?

**Comment by winkelsdorf** [comment] 2023-07-24 17:36
Closing: This problem has either been fixed by the developer in the meantime or an update has solved it as a side effect. Please reopen this issue and/or submit a new issue if the problem persists.

**Closed by winkelsdorf** 2023-07-24 17:36 UTC
Labels: awaiting reply, under investigation, likely not SDK related, unable to reproduce
