### ISSUE TITLE
Phrase App Inconsistency update error

### ISSUE THREAD

**Issue by swayambhu-banerjee** [phrase/ios-sdk#61] opened 2023-08-24 13:01 UTC
The update translation method throws following error

PhraseUpdateError(underlyingErrors: [PhraseSDK.PhraseInternalError.inconsistentUpdate]
SDK Version : 4.2.0
Xcode version: 14.3
Project URL: https://app.phrase.com/accounts/decathlon/distributions/apac-chopper-app

Code Snippet
<img width="1084" alt="Screenshot 2023-08-24 at 8 39 06 PM" src="https://github.com/phrase/ios-sdk/assets/54625502/bd77a529-ab0d-4af1-90d1-4e08116289f6">

**Comment by winkelsdorf** [comment] 2023-08-26 09:59
Hello @swayambhu-banerjee!

Thank you for the report. If you do a clean install on the Device/Simulator does the error persist? Or does it happen irregularly?

We throw this error only when one of the files requested cannot be retrieved. This can happen e.g. when you update the OTA release while requesting the files.

Let me know if you observe this again!

**Comment by swayambhu-banerjee** [comment] 2023-08-28 01:43
Hello @winkelsdorf 
If i do a clean install on my device the error comes up again. It is inconsistently coming up. 
I tried downloading the release from the Phrase dashboard. It was downloaded didn't face any issue there. 
Also I checked we are not updating the OTA release while requesting the files.

**Comment by winkelsdorf** [comment] 2023-08-30 19:15
@swayambhu-banerjee Thank you for checking! At the moment we can't recreate a problem, but we'll try to rule it out in the future with further tests.

**Comment by hahmed-dev** [comment] 2023-10-06 09:23
Hi @swayambhu-banerjee I was looking into this issue from backend perspective to see if the OTA API the SDK is using has something to do with the cause of this error.

As you have mentioned this error occurs inconsistently we were investigating what can be the source of such variating response. In order to investigate it further and rule out possibilities like iOS SDK not receiving all the files its supposed to from OTA server (which can be one of the causes) we wanted to get some more information specifically around the network logs. Would it be possible for you to reproduce this issue and share the network logs? [Charles](https://www.charlesproxy.com/) is one of the tools that can be used for this. 

With more detail information around http request/response we might be able to narrow down on the origin of this issue.

**Comment by carstenapploft** [comment] 2023-10-24 09:05
Hi @swayambhu-banerjee ,

we have been able to reproduce the inconsistentUpdate error and have released a fix with release [4.3.4](https://github.com/phrase/ios-sdk/releases/tag/4.3.4).

**Comment by swayambhu-banerjee** [comment] 2023-10-24 09:15
Hello everyone will test this out.. Thanks for the support..

**Comment by theSoenke** [comment] 2023-11-03 10:47
Hi @swayambhu-banerjee, this should now be resolved in the latest release https://github.com/phrase/ios-sdk/releases/tag/4.3.4 Could you give it a try? This issue could occur before in some rare cases when fetching one of the strings or stringsdict files would fail due to for example a network error

**Closed by theSoenke** 2023-11-03 10:47 UTC
Labels: under investigation
