### ISSUE TITLE
Preferred language automatically switch to Localization native development region

### ISSUE THREAD

**Issue by kabirkhaan** [phrase/ios-sdk#48] opened 2022-08-22 07:42 UTC
After updating 4.0.1 we are facing an issue that app use `Localization native development region`

Steps to Reproduced: 
- Device language is set `de`
- App Preferred language is set to `de`
- **Randomly after OTA sync,** App uses `en` which is set `Localization native development region`

<img src="https://user-images.githubusercontent.com/25608902/185865865-9b4038a7-ef82-478d-a799-3e338e095d4a.png" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/25608902/185866407-15975cfb-422b-4203-9b21-48c4f2ca8703.png" width=50% height=50%>

**Comment by theSoenke** [comment] 2022-08-31 12:22
Do you maybe have an idea what could be the reason why en translations are showing after the upgrade to 4.0.1 @winkelsdorf?

**Comment by kabirkhaan** [comment] 2022-09-07 17:03
> Do you maybe have an idea what could be the reason why en translations are showing after the upgrade to 4.0.1 @winkelsdorf?


As my understanding it picking up Localization native development region from plist for some reason.

**Comment by winkelsdorf** [comment] 2023-01-15 20:43
@kabirkhaan I tried to reproduce this, but sadly was unable to. 

I would suggest using the callback handler of `updateTranslations` to check for any errors (result is `.failure(error)` where `error.last` gives you the current error) and try log them to see under which circumstances the App falls back to the native development region.

We are validating the downloaded translations (e.g. their version range, release version, the last update timestamp etc) and do a fallback to the MainBundle if nothing valid is found.

Another idea: I can also think of a fallback being done at the Backend side. If it happens in a simulator you could investigate the `Localizable.strings`:

```shell
inside iOS Simulator Library: 
Application Support\com.phrase.phraseSDK\Translations\de-DE.lproj\Localizable.strings
```

That file should contain german strings, if they are translated. It might contain fallback strings (e.g. english strings), if you have set the OTA release to do so.

Also please try to enable the `debugMode` and as said please check the result of the `updateHandler` callback.

@theSoenke Do we have any other reports related to this behaviour (App containing the iOS SDK switching the language by itself randomly)?

**Comment by winkelsdorf** [comment] 2023-07-24 17:36
Closing: This problem has either been fixed by the developer in the meantime or an update has solved it as a side effect. Please reopen this issue and/or submit a new issue if the problem persists.

**Closed by winkelsdorf** 2023-07-24 17:36 UTC
Labels: awaiting reply, unable to reproduce
