### ISSUE TITLE
Hardcoded path in latest release 3.0

### ISSUE THREAD

**Issue by ChristianSteffens** [phrase/ios-sdk#30] opened 2021-01-28 13:47 UTC
I noticed an error while debugging our app with the latest Phrase SDK `3.0`.
There's an hardcoded path in the latest framework @winkelsdorf 
```
error: virtual filesystem overlay file 
'/Users/winkelsdorf/Library/Developer/Xcode/DerivedData/PhraseSDKdbgypdflrqbfdrdzewelqaanicsg/
 Build/Intermediates.noindex/ArchiveIntermediates/PhraseSDK/IntermediateBuildFilesPath/
 PhraseSDK.build/Release-iphoneos/PhraseSDK.build/all-product-headers.yaml' not found
```

**Comment by winkelsdorf** [comment] 2021-01-28 13:51
@ChristianSteffens Thank you for the report! Going to investigate this immediately. I can already say that we don't use any hardcoded paths or `.yaml` files. Looks like it might be related to a llvm issue.

How are you integrating the framework? Are you using Carthage?

**Comment by Schlabbi** [comment] 2021-01-28 13:56
Same issue here, this completely broke LLDB commands for my entire app. Had to downgrade to 2.3.0 to be able to use LLDB again.

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/13185384/106148028-db691980-6178-11eb-8839-d9a02dbf6053.png">

Integrating the framework on my part was done using Cocoapods.

**Comment by winkelsdorf** [comment] 2021-01-28 13:58
@Schlabbi Thanks for your additional feedback! 

I'll keep you updated here.

**Comment by ChristianSteffens** [comment] 2021-01-28 14:24
> How are you integrating the framework? Are you using Carthage?

We're using cocoapods.

**Comment by winkelsdorf** [comment] 2021-01-28 14:32
@ChristianSteffens @Schlabbi I'm able to reproduce this error. From what I'd found it is an error related to the generated dSYMS on Xcode 12 (see https://bugs.swift.org/browse/SR-12933). Trying to workaround that now.

**Comment by winkelsdorf** [comment] 2021-01-29 09:52
@ChristianSteffens @Schlabbi Thank you very much for reporting and giving more details! 👍 

I was able to identify the underlying issue. It is a regression in the Swift frontend compiler which leads to issues with the generated dSYMs despite using `-no-serialize-debugging-options` (see https://bugs.swift.org/browse/SR-12933 and https://steipete.com/posts/couldnt-irgen-expression/ for more details if you are curious). 

The hardcoded path has always been included inside the dSYMs, but `-no-serialize-debugging-options` was used to ignore them when debugging. This is now broken with Xcode 12 (12.4?).

The shortly available hotfix release v3.0.1 will omit including the dSYMs. We're going to report this to Apple.

Let me know if this solves the issue for you.

**Comment by winkelsdorf** [comment] 2021-01-29 15:30
@ChristianSteffens @Schlabbi v3.0.1 with a Hotfix is available now

**Comment by gutaker** [comment] 2021-02-04 15:34
`3.0.1` works like a charm. No errors, can debug now.
Good job!

**Comment by winkelsdorf** [comment] 2021-02-05 08:12
@gutaker Glad to hear that it's working for you now. Thank you very much for the feedback, I really appreciate that! Closing this issue now :)

**Closed by winkelsdorf** 2021-02-05 08:12 UTC
Labels: awaiting reply, bug
